# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Fedoriaka-Quantum-Constant-Adder',
                'doc_host': 'https://ShreyanshBanerjee.github.io',
                'git_url': 'https://github.com/ShreyanshBanerjee/Fedoriaka-Quantum-Constant-Adder',
                'lib_path': 'Fedoriaka_Quantum_Constant_Adder'},
  'syms': { 'Fedoriaka_Quantum_Constant_Adder.core': { 'Fedoriaka_Quantum_Constant_Adder.core.Controlled_FedoriakaConstantAdder': ( 'core.html#controlled_fedoriakaconstantadder',
                                                                                                                                    'Fedoriaka_Quantum_Constant_Adder/core.py'),
                                                       'Fedoriaka_Quantum_Constant_Adder.core.FedoriakaConstantAdder': ( 'core.html#fedoriakaconstantadder',
                                                                                                                         'Fedoriaka_Quantum_Constant_Adder/core.py'),
                                                       'Fedoriaka_Quantum_Constant_Adder.core.run': ( 'core.html#run',
                                                                                                      'Fedoriaka_Quantum_Constant_Adder/core.py')}}}
