# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Fedoriaka-Quantum-Constant-Adder',
                'doc_host': 'https://ShreyanshBanerjee.github.io',
                'git_url': 'https://github.com/ShreyanshBanerjee/Fedoriaka-Quantum-Constant-Adder',
                'lib_path': 'Fedoriaka_Quantum_Constant_Adder'},
  'syms': { 'Fedoriaka_Quantum_Constant_Adder.core': { 'Fedoriaka_Quantum_Constant_Adder.core.foo': ( 'core.html#foo',
                                                                                                      'Fedoriaka_Quantum_Constant_Adder/core.py')}}}
