# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['run', 'FedoriakaConstantAdder', 'Controlled_FedoriakaConstantAdder']

# %% ../nbs/00_core.ipynb #540cebb1
from qiskit import QuantumCircuit, transpile
from qiskit.circuit import QuantumRegister, ClassicalRegister
from qiskit_aer import AerSimulator

def run(qc, shots):
  simulator = AerSimulator()
  tqc = transpile(qc, simulator, optimization_level=3)

  job = simulator.run(tqc, shots=shots)
  result = job.result()

  return dict(sorted(result.get_counts().items()))

# %% ../nbs/00_core.ipynb #731329f8
def FedoriakaConstantAdder(constant: int, size: int) -> QuantumCircuit:
  """
  Implements |b> -> |(b + a) mod 2^N> v
    Where a is a fixed classical constant
    Via the method outlined in:
     "New Circuit for Quantum Adder by Constant" (Dmytro Fedoriaka)

  Args:
    constant (int):
      Fixed classical value to add, where 0 <= constant < 2^size a
    size (int):
      Number of qubits in the register b (0<size)

  Result:
    QuantumCircuit object implementing in-place constant addition
    Takes size-3 additional ancillae qubits (or 0 for size<4)  and 1 classical bit (used in uncomputation through venting)
    Can be applied to circuits via .compose()  - .append() will not work

  Circuit Register Layout:
    [ input_qubits | ancillae_qubits ] [ venting_clbit ]
  """
  if size == 1:
    return ConstantAdder_Size1(constant)
  if size == 2:
    return ConstantAdder_Size2(constant)
  if size == 3:
    return ConstantAdder_Size3(constant)
  return ConstantAdder_SizeN(constant, size)

# %% ../nbs/00_core.ipynb #6f7b6add
def Controlled_FedoriakaConstantAdder(constant, size):
  """
  Implements |c>|b> -> |c>|(b + c*a) mod 2^N>
    Where a is a fixed classical constant
      and c is a quantum control bit
    Via the method for a controlled-adder outlined in:
     "New Circuit for Quantum Adder by Constant" (Dmytro Fedoriaka)

  Args:
    constant (int):
      Fixed classical value to add, where 0 <= constant < 2^size a
    size (int):
      Number of qubits in the register b (0<size)

  Result:
    QuantumCircuit object implementing in-place controlled constant addition
    Takes 1 control bit, size-2 additional ancillae qubits (or 0 for size<3), and 1 classical bit (used in uncomputation through venting)
    Can be applied to circuits via .compose()  - .append() will not work

  Circuit Register Layout:
    [ control_qubit | input_qubits | ancillae_qubits ] [ venting_clbit ]
  """
  if size == 1:
    return Controlled_ConstantAdder_Size1(constant)
  if size == 2:
    return Controlled_ConstantAdder_Size2(constant)
  return Controlled_ConstantAdder_SizeN(constant, size)
