# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['FedoriakaConstantAdder', 'Controlled_FedoriakaConstantAdder']

# %% ../nbs/00_core.ipynb #3f459ee0
from qiskit import QuantumCircuit, transpile
from qiskit.circuit import QuantumRegister, ClassicalRegister
from qiskit_aer import AerSimulator

# %% ../nbs/00_core.ipynb #6eb6eb77
def _AND():
  #[a b T] -> [a b a&b]
  qc = QuantumCircuit(3)
  qc.cx(0, 2)
  qc.cx(1, 2)
  qc.cx(2, [0,1])
  qc.tdg([0,1])
  qc.t(2)
  qc.cx(2, [0,1])
  qc.h(2)
  qc.s(2)
  return qc.to_gate(label='ADD')

def _ANDdg():
  #[a b a&b] -> [a b 0]
  qc = QuantumCircuit(3,1)
  qc.h(2)
  qc.measure(2,0)
  with qc.if_test((0, 1)):
    qc.cz(0, 1)
    qc.x(2)
  return qc

# %% ../nbs/00_core.ipynb #31cdfa61
def _convertToBits(i, padding=0):
  #returns padded list of bits in big-endian
  i_bitstr = bin(i)[2:]
  return [int(i) for i in i_bitstr[::-1]]+[0 for i in range(padding-len(i_bitstr))]

#base cases for size=1,2,3 must be done by hand
#luckily, these cases are simple
def _ConstantAdder_Size1(constant):
  a = _convertToBits(constant,1)
  qc = QuantumCircuit(1)
  if a[0] == 1:
    qc.x(0)
  return qc

def _ConstantAdder_Size2(constant):
  a = _convertToBits(constant,2)
  qc = QuantumCircuit(2)
  if a[1] == 1:
    qc.x(1)
  qc.cx(0,1)
  if a[0] == 1:
    qc.x(0)
  return qc

def _ConstantAdder_Size3(constant):
  a = _convertToBits(constant,3)
  qc = QuantumCircuit(3)
  if a[1] == 1:
    qc.x(0)
    qc.x(1)
  qc.mcx([0,1], 2)
  if a[1] == 1:
    qc.x(0)
  qc.cx(0,1)
  if a[0] == 1:
    qc.x(0)
  if a[2]+a[1] == 1: #XOR
    qc.x(2)
  return qc

# %% ../nbs/00_core.ipynb #6628855d
def _ConstantAdder_SizeN(constant, size):
  a = _convertToBits(constant, size)

  b = QuantumRegister(size)
  ancilla = QuantumRegister(size-3)
  cl = ClassicalRegister(1)
  qc = QuantumCircuit(b,ancilla,cl)

  qc.h(ancilla)
  qc.t(ancilla)
  qc.append(_AdderBlock(a[1]), [b[0],b[1],ancilla[0]])
  for i in range(1, size-3):
    qc.append(_AdderBlock(a[i+1]), [ancilla[i-1],b[i+1],ancilla[i]])

  if a[-2] == 1:
    qc.x(b[-2])
    qc.x(ancilla[-1])
  qc.mcx([ancilla[-1], b[-2]], b[-1])
  if a[-2] == 1:
    qc.x(ancilla[-1])
  qc.cx(ancilla[-1], b[-2])
  if a[-1] + a[-2] == 1:
    qc.x(b[-1])

  for i in range(1, size-3)[::-1]:
    qc.compose(_AdderBlockUncompute_op(a[i+1]), qubits=[ancilla[i-1],b[i+1],ancilla[i]], clbits=cl, inplace=True)
  qc.compose(_AdderBlockUncompute_op(a[1]), qubits=[b[0],b[1],ancilla[0]], clbits=cl, inplace=True)
  if a[0] == 1:
    qc.x(0)

  return qc

# %% ../nbs/00_core.ipynb #d489a3a8
def FedoriakaConstantAdder(constant: int, size: int) -> QuantumCircuit:
  """
  Implements |b> -> |(b + a) mod 2^N> v
    Where a is a fixed classical constant
    Via the method outlined in:
     "New Circuit for Quantum Adder by Constant" (Dmytro Fedoriaka)

  Args:
    constant (int):
      Fixed classical value to add, where 0 <= constant < 2^size a
    size (int):
      Number of qubits in the register b (0<size)

  Result:
    QuantumCircuit object implementing in-place constant addition
    Takes size-3 additional ancillae qubits (or 0 for size<4)  and 1 classical bit (used in uncomputation through venting)
    Can be applied to circuits via .compose()  - .append() will not work

  Circuit Register Layout:
    [ input_qubits | ancillae_qubits ] [ venting_clbit ]
  """
  if size == 1:
    return _ConstantAdder_Size1(constant)
  if size == 2:
    return _ConstantAdder_Size2(constant)
  if size == 3:
    return _ConstantAdder_Size3(constant)
  return _ConstantAdder_SizeN(constant, size)

# %% ../nbs/00_core.ipynb #57fef053
def _ControlledAdderBlock(constant_bit):
  qc = QuantumCircuit(4)
  if constant_bit:
    qc.x(1)
    qc.cx(0,2)
  qc.append(_AND(), [1,2,3])
  if constant_bit:
    qc.x(3)
  return qc.to_gate(label='add_block')


def _ControlledAdderBlockUncompute_op(constant_bit):
  qc = QuantumCircuit(4, 1)
  if constant_bit:
    qc.x(3)
  qc.compose(_ANDdg(), qubits=[1,2,3], clbits=[0], inplace=True)
  if constant_bit:
    qc.x(1)
  qc.mcx([0,1],2)

  return qc

# %% ../nbs/00_core.ipynb #1813e147
def _Controlled_ConstantAdder_Size1(constant):
  a = _convertToBits(constant,1)
  qc = QuantumCircuit(2)
  if a[0] == 1:
    qc.cx(0,1)
  return qc

def _Controlled_ConstantAdder_Size2(constant):
  a = _convertToBits(constant,2)
  qc = QuantumCircuit(3)
  if a[1] == 1:
    qc.cx(0,2)
  qc.mcx([0,1],2)
  if a[0] == 1:
    qc.cx(0,1)
  return qc

# %% ../nbs/00_core.ipynb #c0893b6b
def _Controlled_ConstantAdder_SizeN(constant, size):
  a = _convertToBits(constant, size)

  control = [0]
  b = [1+i for i in range(0,size)]
  ancilla = [1+size+i for i in range(0,size-2)]
  qc = QuantumCircuit(2*size-1, 1)

  qc.h(ancilla)
  qc.t(ancilla)

  if a[1] == 1:
    qc.cx(control[0], b[0])
    qc.cx(control[0], b[1])
  qc.compose(_AND(), qubits=[b[0],b[1],ancilla[0]], inplace=True)
  if a[1] == 1:
    qc.x(ancilla[0])

  for i in range(1,size-2):
    qc.compose(_ControlledAdderBlock(a[i+1]), qubits=[control[0],ancilla[i-1], b[i+1], ancilla[i]],inplace=True)

  if a[-2] == 1:
    qc.x(ancilla[-1])
  qc.mcx([control[0], ancilla[-1]], b[-1])
  if a[-2] == 1:
    qc.x(ancilla[-1])
  for i in range(1,size-2)[::-1]:
    qc.compose(_ControlledAdderBlockUncompute_op(a[i+1]), qubits=[control[0], ancilla[i-1], b[i+1], ancilla[i]], clbits=[0], inplace=True)

  if a[1] == 1:
    qc.x(ancilla[0])
  qc.compose(_ANDdg(), qubits=[b[0],b[1],ancilla[0]], clbits=[0], inplace=True)
  if a[1] == 1:
    qc.cx(control[0], b[0])
  qc.mcx([control[0],b[0]], b[1])

  if a[-1]+a[-2]==1:
    qc.cx(control[0],b[-1])
  if a[0]==1:
    qc.cx(control[0],b[0])

  return qc

# %% ../nbs/00_core.ipynb #18aeb8e9
def Controlled_FedoriakaConstantAdder(constant, size):
  """
  Implements |c>|b> -> |c>|(b + c*a) mod 2^N>
    Where a is a fixed classical constant
      and c is a quantum control bit
    Via the method for a controlled-adder outlined in:
     "New Circuit for Quantum Adder by Constant" (Dmytro Fedoriaka)

  Args:
    constant (int):
      Fixed classical value to add, where 0 <= constant < 2^size a
    size (int):
      Number of qubits in the register b (0<size)

  Result:
    QuantumCircuit object implementing in-place controlled constant addition
    Takes 1 control bit, size-2 additional ancillae qubits (or 0 for size<3), and 1 classical bit (used in uncomputation through venting)
    Can be applied to circuits via .compose()  - .append() will not work

  Circuit Register Layout:
    [ control_qubit | input_qubits | ancillae_qubits ] [ venting_clbit ]
  """
  if size == 1:
    return _Controlled_ConstantAdder_Size1(constant)
  if size == 2:
    return _Controlled_ConstantAdder_Size2(constant)
  return _Controlled_ConstantAdder_SizeN(constant, size)
